Add editor's note about relation b/t OBI & CHEBI: solvent/solvent role
obi-ontology/obi pull request #1778
Opened 2024-04-08 18:51 UTC by sebastianduesing

Closes #1771. Adds an editor's note to OBI:"solvent role" specifying the difference between it and CHEBI:"solvent," using language proposed by @bpeters42.

2024-04-15 16:43 UTC, bpeters42 approved these changes
reviewed in OBI call 4/15

2024-04-22 16:53 UTC, turbomam commented
An editor note like this is a good way of adding clarity, but I beleive that, as of April 2024, roles and material entities are disjoint in ChEBI, and this particular editor note is actually misleading.

2024-04-22 OBI call
It is concerning that roles and material entities in ChEBI may have been less clear in the past, and if a change was made, we don't know about it in this OBI call.

2024-04-23 03:51 UTC, cmungall requested changes
I agree with @turbomam. In fact these branches have always been disjoint.

2024-04-23 16:51 UTC, bpeters42 commented
I cannot reconstruct what I had looked at before, and @turbomam and @cmungall are completely right. We should not add this comment, and go back to the issue.

2024-04-29 16:32 UTC, closed without merging

2024-04-29 16:32 UTC, bpeters42 commented
Closing this PR to revisit the discussion on the issue itself.